# パッケージ名
name = "banner"

# パッケージバージョン (SemVer 形式)
version = "1.0.40"

# パッケージの説明
description = "banner"

# 作者名
author = "dai.motoki"

# 作者のメールアドレス
email = "motoki.daisuke@kandaquantum.co.jp"

# パッケージのライセンス
license = "MIT"

# Supabase Storage 上のファイルパス (アップロード後に設定されます)
# file_path = "banner/1.0.31/banner.tar.gz"

# その他の項目 (任意)
language = "python"
category = "ai"
tags = ["tool", "development"]
homepage = "https://example.com/banner"
repository = "https://github.com/your-username/banner"
readme = """
# Banner

これはサンプルです。
"""
dependencies = "{ \"requests\" : \"^2.28.1\" }"
# End of Selection
