# パッケージ名
name = "i18niwatoko"

# パッケージバージョン (SemVer 形式)
version = "1.0.0"

# パッケージの説明
description = "多言語翻訳ツール"

# 作者名
author = "dai.motoki"

# 作者のメールアドレス
email = "motoki.daisuke@kandaquantum.co.jp"

# パッケージのライセンス
license = "MIT"

# Supabase Storage 上のファイルパス (アップロード後に設定されます)
# file_path = "i18niwatoko/1.0.0/i18niwatoko.tar.gz"

# その他の項目 (任意)
language = "python"
category = "utilities"
tags = ["translation", "i18n"]
homepage = "https://example.com/i18niwatoko"
repository = "https://github.com/your-username/i18niwatoko"
readme = """
# i18niwatoko

多言語翻訳ツールです。

grimo install i18niwatoko

```
- i18niwatoko = [i18niwatoko]
- 元ファイル = [./翻訳したいファイル]

"""
dependencies = "{ \"rich\" : \"^13.3.5\", \"claude3\" : \"^1.0.0\" }"
# End of Selection

