name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v2

      - name: セットアップPython
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: 環境変数を設定 # 追加
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV 

      - name: 依存関係をインストール
        run: |
          pip install openai grimo niwatoko
          niwatoko -v 
          grimo install i18niwatoko

      - name: 作業ディレクトリの確認
        run: ls /opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/grimo/grimoires/i18niwatoko/1.0.0
      - name: テストを実行
        run: |
          cd tests
          niwatoko def.md -o exe.md
