name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v2

      - name: セットアップPython
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 環境変数を設定
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV 

      - name: 依存関係をインストール
        run: |
          pip install --upgrade grimo niwatoko
          niwatoko -v 
          grimo install i18niwatoko

      - name: テストサーバー起動
        run: |
          cd auth
          uvicorn server:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: テストを実行
        run: |
          cd tests
          niwatoko def.md -o exe.md

  grimo-cli-tests:
    runs-on: ubuntu-latest
    needs: test  # test ジョブの後に実行
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v2

      - name: セットアップPython
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 依存関係をインストール
        run: |
          pip install -r requirements.txt
          pip install -e .  # grimo パッケージを編集可能モードでインストール

      - name: ログインテスト
        run: |
          echo "test@example.com" | grimo login --server-url "http://localhost:8000"
          echo "password" | grimo login --server-url "http://localhost:8000"

      - name: パッケージアップロードテスト
        run: |
          grimo --server-url "http://localhost:8000" upload test-package

      - name: パッケージ検索テスト
        run: |
          grimo --server-url "http://localhost:8000" search test-package

      - name: パッケージインストールテスト
        run: |
          grimo --server-url "http://localhost:8000" install test-package

      - name: パッケージアップデートテスト
        run: |
          grimo --server-url "http://localhost:8000" update test-package

      - name: パッケージアンインストールテスト
        run: |
          grimo --server-url "http://localhost:8000" uninstall test-package

      - name: インストール済みパッケージ一覧表示テスト
        run: |
          grimo --server-url "http://localhost:8000" list